/*
  # Create Curated Home Organization Tables, Seed Function, and Backfill

  ## Summary
  This migration sets up the full home organization curated data system, exactly
  mirroring the checklist pattern already in production.

  ## New Tables

  ### curated_home_org_categories
  - `id` (text, primary key) - Slug identifier (e.g., "daily-reset-adhd")
  - `name` (text) - Display name
  - `icon_name` (text) - Lucide React icon name
  - `color_tag` (text) - Hex color for the category
  - `sort_order` (int) - Display order (1-21)

  ### curated_home_org_items
  - `id` (uuid, primary key)
  - `category_id` (text, FK to curated_home_org_categories)
  - `title` (text) - Task text
  - `order_index` (int) - 0-based position within category

  ## New Functions
  - `seed_home_org_for_user(p_user_id UUID)` - Seeds all 840 individual task rows
    into organization_tasks for a given user. Idempotent via ON CONFLICT DO NOTHING.

  ## Security
  - Both curated tables have RLS enabled with a public authenticated SELECT policy
    so the seed function can read them
  - Seed function runs as SECURITY DEFINER

  ## Notes
  1. All 21 categories and 840 items (40 per category) are inserted in this migration
  2. A unique constraint is added to organization_tasks(user_id, section, title)
     to support idempotent seeding
  3. All existing users are backfilled immediately
*/

-- ────────────────────────────────────────────────────────────────────────────
-- 1. Curated categories table
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS curated_home_org_categories (
  id         text PRIMARY KEY,
  name       text NOT NULL,
  icon_name  text NOT NULL DEFAULT 'Home',
  color_tag  text NOT NULL DEFAULT '#C9A962',
  sort_order int  NOT NULL DEFAULT 99
);

ALTER TABLE curated_home_org_categories ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'curated_home_org_categories'
      AND policyname = 'Anyone authenticated can read curated home org categories'
  ) THEN
    CREATE POLICY "Anyone authenticated can read curated home org categories"
      ON curated_home_org_categories FOR SELECT
      TO authenticated
      USING (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────────────────
-- 2. Curated items table
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS curated_home_org_items (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id text NOT NULL REFERENCES curated_home_org_categories(id) ON DELETE CASCADE,
  title       text NOT NULL,
  order_index int  NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS curated_home_org_items_category_idx ON curated_home_org_items(category_id);

ALTER TABLE curated_home_org_items ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'curated_home_org_items'
      AND policyname = 'Anyone authenticated can read curated home org items'
  ) THEN
    CREATE POLICY "Anyone authenticated can read curated home org items"
      ON curated_home_org_items FOR SELECT
      TO authenticated
      USING (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────────────────
-- 3. Insert 21 categories
-- ────────────────────────────────────────────────────────────────────────────
INSERT INTO curated_home_org_categories (id, name, icon_name, color_tag, sort_order) VALUES
  ('daily-reset-adhd',         'Daily Reset (ADHD Quick Wins)',  'Sparkles',       '#F59E0B', 1),
  ('weekly-cleaning',          'Weekly Cleaning',                'Calendar',       '#3B82F6', 2),
  ('monthly-deep-clean',       'Monthly Deep Clean',             'Brush',          '#EF4444', 3),
  ('seasonal-reset',           'Seasonal Reset',                 'Leaf',           '#10B981', 4),
  ('kitchen-organization',     'Kitchen Organization',           'ChefHat',        '#F59E0B', 5),
  ('pantry-organization',      'Pantry Organization',            'Package',        '#8B5CF6', 6),
  ('refrigerator-freezer',     'Refrigerator & Freezer',         'Refrigerator',   '#06B6D4', 7),
  ('bedroom-organization',     'Bedroom Organization',           'Bed',            '#EC4899', 8),
  ('closet-organization',      'Closet Organization',            'Shirt',          '#3B82F6', 9),
  ('bathroom-organization',    'Bathroom Organization',          'Bath',           '#14B8A6', 10),
  ('linen-closet',             'Linen Closet',                   'Layers',         '#A855F7', 11),
  ('laundry-room',             'Laundry Room',                   'WashingMachine', '#0EA5E9', 12),
  ('living-room-common-areas', 'Living Room / Common Areas',     'Sofa',           '#F97316', 13),
  ('entryway-mudroom',         'Entryway / Mudroom',             'Door',           '#84CC16', 14),
  ('home-office-desk',         'Home Office / Desk',             'Monitor',        '#6366F1', 15),
  ('storage-areas',            'Storage Areas',                  'Archive',        '#78716C', 16),
  ('garage',                   'Garage',                         'Car',            '#0D9488', 17),
  ('under-bed-hidden-storage', 'Under-Bed / Hidden Storage',     'Package',        '#E11D48', 18),
  ('digital-home-organization','Digital Home Organization',      'Smartphone',     '#6366F1', 19),
  ('decluttering-donation-prep','Decluttering & Donation Prep',  'Recycle',        '#10B981', 20),
  ('moving-reset-checklist',   'Moving / Reset Checklist',       'Truck',          '#F59E0B', 21)
ON CONFLICT (id) DO UPDATE SET
  name       = EXCLUDED.name,
  icon_name  = EXCLUDED.icon_name,
  color_tag  = EXCLUDED.color_tag,
  sort_order = EXCLUDED.sort_order;

-- ────────────────────────────────────────────────────────────────────────────
-- 4. Insert 840 items (40 per category)
-- ────────────────────────────────────────────────────────────────────────────
DELETE FROM curated_home_org_items;

INSERT INTO curated_home_org_items (category_id, title, order_index) VALUES
-- daily-reset-adhd
('daily-reset-adhd','Make bed (pillows + comforter)',0),
('daily-reset-adhd','Put clothes in hamper',1),
('daily-reset-adhd','Clear nightstand',2),
('daily-reset-adhd','Load dishwasher',3),
('daily-reset-adhd','Wipe kitchen counters',4),
('daily-reset-adhd','Put items back in their place',5),
('daily-reset-adhd','Quick bathroom sink wipe',6),
('daily-reset-adhd','Take out trash if full',7),
('daily-reset-adhd','Spot vacuum high-traffic areas',8),
('daily-reset-adhd','Straighten throw pillows',9),
('daily-reset-adhd','Hang up towels',10),
('daily-reset-adhd','Check mail and sort',11),
('daily-reset-adhd','Rinse dirty dishes',12),
('daily-reset-adhd','Wipe stove top',13),
('daily-reset-adhd','Empty sink of dishes',14),
('daily-reset-adhd','Fold clean laundry',15),
('daily-reset-adhd','Put away shoes',16),
('daily-reset-adhd','Clear dining table',17),
('daily-reset-adhd','Fluff couch cushions',18),
('daily-reset-adhd','Close all cabinet doors',19),
('daily-reset-adhd','Refill water bottle',20),
('daily-reset-adhd','Charge electronics',21),
('daily-reset-adhd','Quick floor sweep',22),
('daily-reset-adhd','Organize remote controls',23),
('daily-reset-adhd','Put away toiletries',24),
('daily-reset-adhd','Check for stray items',25),
('daily-reset-adhd','Open blinds or curtains',26),
('daily-reset-adhd','Water plants',27),
('daily-reset-adhd','Clear coffee table',28),
('daily-reset-adhd','Tidy entryway',29),
('daily-reset-adhd','Put away paperwork',30),
('daily-reset-adhd','Check calendar for tomorrow',31),
('daily-reset-adhd','Set out tomorrow outfit',32),
('daily-reset-adhd','Quick desk clear',33),
('daily-reset-adhd','Put books back on shelf',34),
('daily-reset-adhd','Wipe bathroom mirror',35),
('daily-reset-adhd','Empty small trash cans',36),
('daily-reset-adhd','Replace hand towels if dirty',37),
('daily-reset-adhd','Close all drawers',38),
('daily-reset-adhd','Quick pet area tidy',39),
-- weekly-cleaning
('weekly-cleaning','Vacuum all floors',0),
('weekly-cleaning','Mop hard floors',1),
('weekly-cleaning','Clean toilet (bowl + seat)',2),
('weekly-cleaning','Clean bathroom sink & mirror',3),
('weekly-cleaning','Change bed sheets',4),
('weekly-cleaning','Wipe appliances (microwave, fridge handles)',5),
('weekly-cleaning','Dust surfaces',6),
('weekly-cleaning','Take out recycling',7),
('weekly-cleaning','Wipe light switches & doorknobs',8),
('weekly-cleaning','Empty all trash bins',9),
('weekly-cleaning','Clean shower & bathtub',10),
('weekly-cleaning','Wash bathroom rugs',11),
('weekly-cleaning','Dust ceiling fans',12),
('weekly-cleaning','Wipe window sills',13),
('weekly-cleaning','Clean inside trash cans',14),
('weekly-cleaning','Vacuum furniture',15),
('weekly-cleaning','Wipe kitchen table & chairs',16),
('weekly-cleaning','Clean stovetop thoroughly',17),
('weekly-cleaning','Wipe refrigerator exterior',18),
('weekly-cleaning','Disinfect kitchen sink',19),
('weekly-cleaning','Clean coffee maker',20),
('weekly-cleaning','Wash dish towels & sponges',21),
('weekly-cleaning','Vacuum under furniture',22),
('weekly-cleaning','Clean pet bowls thoroughly',23),
('weekly-cleaning','Wipe down door frames',24),
('weekly-cleaning','Clean TV screen',25),
('weekly-cleaning','Vacuum air vents',26),
('weekly-cleaning','Wipe all mirrors',27),
('weekly-cleaning','Clean bathroom counters',28),
('weekly-cleaning','Organize junk drawer',29),
('weekly-cleaning','Wipe cabinet fronts',30),
('weekly-cleaning','Clean entryway mat',31),
('weekly-cleaning','Spot clean walls',32),
('weekly-cleaning','Dust picture frames',33),
('weekly-cleaning','Clean kitchen trash can',34),
('weekly-cleaning','Vacuum stairs',35),
('weekly-cleaning','Wipe bathroom fixtures',36),
('weekly-cleaning','Clean toothbrush holder',37),
('weekly-cleaning','Wipe down remotes',38),
('weekly-cleaning','Organize mail pile',39),
-- monthly-deep-clean
('monthly-deep-clean','Clean inside microwave',0),
('monthly-deep-clean','Clean inside refrigerator',1),
('monthly-deep-clean','Wipe baseboards',2),
('monthly-deep-clean','Clean shower walls & grout',3),
('monthly-deep-clean','Wash shower curtain or liner',4),
('monthly-deep-clean','Clean windows & mirrors thoroughly',5),
('monthly-deep-clean','Declutter junk drawers',6),
('monthly-deep-clean','Organize pantry shelves',7),
('monthly-deep-clean','Vacuum mattress & flip if needed',8),
('monthly-deep-clean','Wipe cabinet doors & handles',9),
('monthly-deep-clean','Deep clean oven',10),
('monthly-deep-clean','Clean dishwasher filter',11),
('monthly-deep-clean','Clean washing machine',12),
('monthly-deep-clean','Scrub toilet thoroughly',13),
('monthly-deep-clean','Clean behind appliances',14),
('monthly-deep-clean','Dust light fixtures',15),
('monthly-deep-clean','Clean exhaust fans',16),
('monthly-deep-clean','Wipe down walls',17),
('monthly-deep-clean','Deep clean kitchen cabinets inside',18),
('monthly-deep-clean','Clean under sink areas',19),
('monthly-deep-clean','Vacuum refrigerator coils',20),
('monthly-deep-clean','Clean range hood & filter',21),
('monthly-deep-clean','Shampoo carpets',22),
('monthly-deep-clean','Clean outdoor furniture',23),
('monthly-deep-clean','Wash pillows',24),
('monthly-deep-clean','Deep clean bathroom tiles',25),
('monthly-deep-clean','Organize closets',26),
('monthly-deep-clean','Clean window tracks',27),
('monthly-deep-clean','Wipe down washer & dryer',28),
('monthly-deep-clean','Clean dryer vent',29),
('monthly-deep-clean','Dust ceiling corners for cobwebs',30),
('monthly-deep-clean','Clean door mats & rugs',31),
('monthly-deep-clean','Organize medicine cabinet',32),
('monthly-deep-clean','Clean jewelry',33),
('monthly-deep-clean','Wipe down furniture legs',34),
('monthly-deep-clean','Clean under furniture cushions',35),
('monthly-deep-clean','Organize garage shelves',36),
('monthly-deep-clean','Clean garage floor',37),
('monthly-deep-clean','Check smoke detectors',38),
('monthly-deep-clean','Replace air filters',39),
-- seasonal-reset
('seasonal-reset','Rotate seasonal clothes in closet',0),
('seasonal-reset','Wash & store winter/summer bedding',1),
('seasonal-reset','Deep clean windows (inside & out)',2),
('seasonal-reset','Declutter & donation sweep',3),
('seasonal-reset','Clean ceiling fans & light fixtures',4),
('seasonal-reset','Organize garage or storage space',5),
('seasonal-reset','Vacuum/wash curtains & blinds',6),
('seasonal-reset','Check & replace air filters',7),
('seasonal-reset','Reorganize holiday decorations',8),
('seasonal-reset','Flip mattress',9),
('seasonal-reset','Clean gutters',10),
('seasonal-reset','Power wash exterior',11),
('seasonal-reset','Service HVAC system',12),
('seasonal-reset','Check weather stripping',13),
('seasonal-reset','Clean outdoor grill',14),
('seasonal-reset','Store outdoor cushions',15),
('seasonal-reset','Winterize or summer-prep garden',16),
('seasonal-reset','Deep clean patio or deck',17),
('seasonal-reset','Organize tool shed',18),
('seasonal-reset','Check for drafts around doors',19),
('seasonal-reset','Clean chimney or fireplace',20),
('seasonal-reset','Switch out seasonal decor',21),
('seasonal-reset','Wash all throw blankets',22),
('seasonal-reset','Vacuum heating vents',23),
('seasonal-reset','Check carbon monoxide detectors',24),
('seasonal-reset','Clean and store fans',25),
('seasonal-reset','Organize seasonal sports gear',26),
('seasonal-reset','Inspect roof for damage',27),
('seasonal-reset','Trim bushes and trees',28),
('seasonal-reset','Seal driveway cracks',29),
('seasonal-reset','Clean window screens',30),
('seasonal-reset','Organize attic or basement',31),
('seasonal-reset','Check insulation',32),
('seasonal-reset','Clean outdoor lights',33),
('seasonal-reset','Store summer toys and equipment',34),
('seasonal-reset','Rotate rugs',35),
('seasonal-reset','Deep clean entryway closet',36),
('seasonal-reset','Refresh indoor plants',37),
('seasonal-reset','Clean mailbox',38),
('seasonal-reset','Organize holiday storage bins',39),
-- kitchen-organization
('kitchen-organization','Deep clean oven & stovetop',0),
('kitchen-organization','Wipe cabinet fronts & handles',1),
('kitchen-organization','Declutter utensil drawers',2),
('kitchen-organization','Organize spice drawer/rack',3),
('kitchen-organization','Clean out expired pantry items',4),
('kitchen-organization','Wipe fridge shelves & drawers',5),
('kitchen-organization','Clean sink & disposal',6),
('kitchen-organization','Organize pots & pans',7),
('kitchen-organization','Clean microwave inside & out',8),
('kitchen-organization','Wipe down small appliances',9),
('kitchen-organization','Organize food storage containers',10),
('kitchen-organization','Clean cabinet interiors',11),
('kitchen-organization','Organize baking supplies',12),
('kitchen-organization','Declutter gadget drawer',13),
('kitchen-organization','Clean kitchen vent hood',14),
('kitchen-organization','Organize cutting boards',15),
('kitchen-organization','Clean toaster and crumb tray',16),
('kitchen-organization','Wipe down backsplash',17),
('kitchen-organization','Organize dish towels',18),
('kitchen-organization','Clean dishwasher exterior',19),
('kitchen-organization','Sort through cookbooks',20),
('kitchen-organization','Organize drink storage area',21),
('kitchen-organization','Clean inside drawers',22),
('kitchen-organization','Organize knife block',23),
('kitchen-organization','Declutter under sink area',24),
('kitchen-organization','Match container lids with bases',25),
('kitchen-organization','Clean coffee maker thoroughly',26),
('kitchen-organization','Organize tea and coffee station',27),
('kitchen-organization','Wipe down kitchen table legs',28),
('kitchen-organization','Clean trash can liner and exterior',29),
('kitchen-organization','Organize snack cabinet',30),
('kitchen-organization','Clean blender and accessories',31),
('kitchen-organization','Sort through plastic bags',32),
('kitchen-organization','Organize junk drawer',33),
('kitchen-organization','Clean kitchen light fixture',34),
('kitchen-organization','Wipe down fridge exterior and sides',35),
('kitchen-organization','Organize cleaning supplies under sink',36),
('kitchen-organization','Clean kitchen window',37),
('kitchen-organization','Sort through reusable bags',38),
('kitchen-organization','Organize pet food area',39),
-- pantry-organization
('pantry-organization','Check expiration dates',0),
('pantry-organization','Group similar items together',1),
('pantry-organization','Label containers & bins',2),
('pantry-organization','Wipe shelves',3),
('pantry-organization','Reorganize by frequency of use',4),
('pantry-organization','Donate unused items',5),
('pantry-organization','Take inventory for grocery list',6),
('pantry-organization','Transfer dry goods to airtight containers',7),
('pantry-organization','Clean pantry floor',8),
('pantry-organization','Organize canned goods',9),
('pantry-organization','Arrange snacks in bins',10),
('pantry-organization','Group breakfast items',11),
('pantry-organization','Organize baking supplies',12),
('pantry-organization','Sort pasta and grains',13),
('pantry-organization','Arrange sauces and condiments',14),
('pantry-organization','Create zones by meal type',15),
('pantry-organization','Use shelf risers for visibility',16),
('pantry-organization','Rotate older items to front',17),
('pantry-organization','Organize spices alphabetically',18),
('pantry-organization','Group oils and vinegars',19),
('pantry-organization','Sort beverage mixes',20),
('pantry-organization','Organize kids snack area',21),
('pantry-organization','Check for pest issues',22),
('pantry-organization','Clean pantry door',23),
('pantry-organization','Organize paper goods section',24),
('pantry-organization','Sort tea and coffee supplies',25),
('pantry-organization','Group dessert items',26),
('pantry-organization','Arrange chips and crackers',27),
('pantry-organization','Organize nut and seed storage',28),
('pantry-organization','Clean shelf brackets',29),
('pantry-organization','Add shelf liners if needed',30),
('pantry-organization','Arrange reusable bags',31),
('pantry-organization','Organize lunch box supplies',32),
('pantry-organization','Sort through bulk items',33),
('pantry-organization','Group international foods',34),
('pantry-organization','Organize supplement storage',35),
('pantry-organization','Arrange bread and baked goods area',36),
('pantry-organization','Label expiration dates clearly',37),
('pantry-organization','Create grab-and-go section',38),
('pantry-organization','Organize meal prep ingredients',39),
-- refrigerator-freezer
('refrigerator-freezer','Toss expired food',0),
('refrigerator-freezer','Wipe all shelves & drawers',1),
('refrigerator-freezer','Clean door seals',2),
('refrigerator-freezer','Organize by food type',3),
('refrigerator-freezer','Defrost freezer if needed',4),
('refrigerator-freezer','Label leftovers with dates',5),
('refrigerator-freezer','Clean underneath with vacuum',6),
('refrigerator-freezer','Wipe exterior and handles',7),
('refrigerator-freezer','Clean ice maker',8),
('refrigerator-freezer','Organize condiments on door',9),
('refrigerator-freezer','Group dairy products together',10),
('refrigerator-freezer','Organize produce drawers',11),
('refrigerator-freezer','Check water filter status',12),
('refrigerator-freezer','Clean drip tray',13),
('refrigerator-freezer','Organize beverages',14),
('refrigerator-freezer','Use clear bins for visibility',15),
('refrigerator-freezer','Create meal prep zone',16),
('refrigerator-freezer','Clean door bins',17),
('refrigerator-freezer','Organize deli meats and cheeses',18),
('refrigerator-freezer','Check temperature setting',19),
('refrigerator-freezer','Remove and clean all drawers',20),
('refrigerator-freezer','Organize freezer by category',21),
('refrigerator-freezer','Use freezer bins for organization',22),
('refrigerator-freezer','Label frozen items with date',23),
('refrigerator-freezer','Clean freezer door',24),
('refrigerator-freezer','Organize ice cream and desserts',25),
('refrigerator-freezer','Group frozen vegetables',26),
('refrigerator-freezer','Arrange frozen meals',27),
('refrigerator-freezer','Clean behind fridge',28),
('refrigerator-freezer','Check for frost buildup',29),
('refrigerator-freezer','Organize butter and spreads',30),
('refrigerator-freezer','Clean egg holder',31),
('refrigerator-freezer','Group breakfast items',32),
('refrigerator-freezer','Organize snacks for kids',33),
('refrigerator-freezer','Clean spill guards',34),
('refrigerator-freezer','Organize juice and milk',35),
('refrigerator-freezer','Create leftover section',36),
('refrigerator-freezer','Clean coils behind unit',37),
('refrigerator-freezer','Organize lunch ingredients',38),
('refrigerator-freezer','Remove stale or wilted produce',39),
-- bedroom-organization
('bedroom-organization','Rotate seasonal clothes',0),
('bedroom-organization','Wash bedding & pillows',1),
('bedroom-organization','Vacuum under bed',2),
('bedroom-organization','Declutter nightstand drawers',3),
('bedroom-organization','Organize dresser drawers',4),
('bedroom-organization','Dust ceiling fan & light fixtures',5),
('bedroom-organization','Wipe down furniture',6),
('bedroom-organization','Vacuum mattress',7),
('bedroom-organization','Organize jewelry box',8),
('bedroom-organization','Clean mirrors and glass',9),
('bedroom-organization','Dust window blinds',10),
('bedroom-organization','Organize shoe storage',11),
('bedroom-organization','Declutter dresser top',12),
('bedroom-organization','Wash throw blankets',13),
('bedroom-organization','Organize sock drawer',14),
('bedroom-organization','Fold and store sweaters',15),
('bedroom-organization','Clean out under bed storage',16),
('bedroom-organization','Organize underwear drawer',17),
('bedroom-organization','Dust picture frames',18),
('bedroom-organization','Clean closet floor',19),
('bedroom-organization','Organize charging station',20),
('bedroom-organization','Wash curtains',21),
('bedroom-organization','Clean lamp shades',22),
('bedroom-organization','Organize bedside table',23),
('bedroom-organization','Sort through books on nightstand',24),
('bedroom-organization','Dust baseboards',25),
('bedroom-organization','Clean air vents',26),
('bedroom-organization','Organize accessory drawer',27),
('bedroom-organization','Vacuum closet',28),
('bedroom-organization','Wipe light switches',29),
('bedroom-organization','Organize seasonal bedding storage',30),
('bedroom-organization','Clean bedroom door',31),
('bedroom-organization','Organize beauty products',32),
('bedroom-organization','Declutter dresser drawers',33),
('bedroom-organization','Clean window sills',34),
('bedroom-organization','Organize reading materials',35),
('bedroom-organization','Dust artwork',36),
('bedroom-organization','Clean behind headboard',37),
('bedroom-organization','Organize laundry hamper',38),
('bedroom-organization','Tidy bedside charging cables',39),
-- closet-organization
('closet-organization','Sort clothes by season',0),
('closet-organization','Donate unworn items',1),
('closet-organization','Organize shoes',2),
('closet-organization','Fold & store sweaters',3),
('closet-organization','Hang items by type/color',4),
('closet-organization','Organize accessories drawer',5),
('closet-organization','Vacuum closet floor',6),
('closet-organization','Add cedar balls or sachets',7),
('closet-organization','Use matching hangers',8),
('closet-organization','Organize by outfit type',9),
('closet-organization','Store off-season clothes',10),
('closet-organization','Organize belts on hooks',11),
('closet-organization','Arrange scarves neatly',12),
('closet-organization','Sort through old clothes',13),
('closet-organization','Organize purses and bags',14),
('closet-organization','Use shelf dividers',15),
('closet-organization','Organize jewelry in closet',16),
('closet-organization','Hang hats properly',17),
('closet-organization','Use drawer organizers',18),
('closet-organization','Store workout clothes together',19),
('closet-organization','Organize pajamas',20),
('closet-organization','Sort dress shirts and blouses',21),
('closet-organization','Fold jeans and pants',22),
('closet-organization','Organize formal wear',23),
('closet-organization','Store seasonal accessories',24),
('closet-organization','Use clear shoe boxes',25),
('closet-organization','Label storage bins',26),
('closet-organization','Organize ties and cufflinks',27),
('closet-organization','Hang coats properly',28),
('closet-organization','Use space-saving hangers',29),
('closet-organization','Organize swimwear',30),
('closet-organization','Sort athletic gear',31),
('closet-organization','Organize undergarments',32),
('closet-organization','Store luggage efficiently',33),
('closet-organization','Clean closet shelves',34),
('closet-organization','Organize seasonal shoes',35),
('closet-organization','Use hanging organizers',36),
('closet-organization','Store delicate items properly',37),
('closet-organization','Organize dry cleaning items',38),
('closet-organization','Dust closet rods',39),
-- bathroom-organization
('bathroom-organization','Declutter under-sink storage',0),
('bathroom-organization','Wash bath mats & towels',1),
('bathroom-organization','Clean grout & tiles',2),
('bathroom-organization','Wipe mirrors & glass',3),
('bathroom-organization','Organize skincare & makeup drawer',4),
('bathroom-organization','Toss expired products',5),
('bathroom-organization','Refill toiletries & toilet paper',6),
('bathroom-organization','Organize medicine cabinet',7),
('bathroom-organization','Clean shower drain',8),
('bathroom-organization','Organize hair tools and accessories',9),
('bathroom-organization','Clean toothbrush holder',10),
('bathroom-organization','Wipe down shower caddy',11),
('bathroom-organization','Organize nail care supplies',12),
('bathroom-organization','Sort through cotton swabs and pads',13),
('bathroom-organization','Clean soap dispensers',14),
('bathroom-organization','Organize shampoo and conditioner',15),
('bathroom-organization','Declutter makeup collection',16),
('bathroom-organization','Clean shower curtain rings',17),
('bathroom-organization','Organize first aid supplies',18),
('bathroom-organization','Wipe cabinet doors',19),
('bathroom-organization','Sort through cleaning products',20),
('bathroom-organization','Organize towel storage',21),
('bathroom-organization','Clean tissue box holder',22),
('bathroom-organization','Organize razors and shaving supplies',23),
('bathroom-organization','Sort through sample products',24),
('bathroom-organization','Clean toilet brush holder',25),
('bathroom-organization','Organize hair ties and clips',26),
('bathroom-organization','Wipe light fixtures',27),
('bathroom-organization','Organize bath products',28),
('bathroom-organization','Clean exhaust fan',29),
('bathroom-organization','Sort through nail polish',30),
('bathroom-organization','Organize perfume and cologne',31),
('bathroom-organization','Clean behind toilet',32),
('bathroom-organization','Wipe bathroom hardware',33),
('bathroom-organization','Organize dental care items',34),
('bathroom-organization','Clean shower head',35),
('bathroom-organization','Sort through travel toiletries',36),
('bathroom-organization','Organize hand towels',37),
('bathroom-organization','Clean bathtub overflow',38),
('bathroom-organization','Wipe down countertops thoroughly',39),
-- linen-closet
('linen-closet','Fold & organize towels',0),
('linen-closet','Group sheet sets together',1),
('linen-closet','Add shelf dividers',2),
('linen-closet','Rotate older items to front',3),
('linen-closet','Donate worn linens',4),
('linen-closet','Add lavender sachets',5),
('linen-closet','Organize by size (twin, queen, king)',6),
('linen-closet','Store pillowcases with sheets',7),
('linen-closet','Fold bath towels uniformly',8),
('linen-closet','Organize hand towels separately',9),
('linen-closet','Store washcloths in basket',10),
('linen-closet','Organize beach towels',11),
('linen-closet','Store extra blankets neatly',12),
('linen-closet','Organize tablecloths and napkins',13),
('linen-closet','Clean closet shelves',14),
('linen-closet','Use vacuum bags for seasonal items',15),
('linen-closet','Label shelves clearly',16),
('linen-closet','Organize guest bedding',17),
('linen-closet','Store duvet covers properly',18),
('linen-closet','Fold throw blankets',19),
('linen-closet','Organize kitchen towels',20),
('linen-closet','Store mattress protectors',21),
('linen-closet','Organize pillow protectors',22),
('linen-closet','Store seasonal bedding',23),
('linen-closet','Organize bathroom rugs',24),
('linen-closet','Use baskets for small items',25),
('linen-closet','Store extra pillows',26),
('linen-closet','Organize baby bedding',27),
('linen-closet','Clean and air out closet',28),
('linen-closet','Check for moth damage',29),
('linen-closet','Vacuum closet floor',30),
('linen-closet','Organize ironing board and iron',31),
('linen-closet','Store laundry bags',32),
('linen-closet','Organize cleaning cloths',33),
('linen-closet','Stack items by frequency of use',34),
('linen-closet','Store spa towels separately',35),
('linen-closet','Organize pet bedding',36),
('linen-closet','Use shelf liners',37),
('linen-closet','Store holiday linens',38),
('linen-closet','Keep inventory list',39),
-- laundry-room
('laundry-room','Clean washer & dryer filters',0),
('laundry-room','Wipe down machines',1),
('laundry-room','Organize detergent & supplies',2),
('laundry-room','Sort laundry baskets',3),
('laundry-room','Fold & put away clean clothes',4),
('laundry-room','Sweep & mop floor',5),
('laundry-room','Clean dryer vent thoroughly',6),
('laundry-room','Wipe down folding surface',7),
('laundry-room','Organize stain removal supplies',8),
('laundry-room','Clean lint trap',9),
('laundry-room','Organize laundry sorting bins',10),
('laundry-room','Store ironing supplies',11),
('laundry-room','Clean washing machine drum',12),
('laundry-room','Organize fabric softener and dryer sheets',13),
('laundry-room','Wipe cabinets and shelves',14),
('laundry-room','Clean behind machines',15),
('laundry-room','Organize clothespins and hangers',16),
('laundry-room','Store laundry bags',17),
('laundry-room','Clean utility sink',18),
('laundry-room','Organize lost sock basket',19),
('laundry-room','Wipe light fixtures',20),
('laundry-room','Clean baseboards',21),
('laundry-room','Organize drying rack',22),
('laundry-room','Store mesh laundry bags',23),
('laundry-room','Clean laundry room door',24),
('laundry-room','Organize delicates wash supplies',25),
('laundry-room','Wipe down countertops',26),
('laundry-room','Clean washer door seal',27),
('laundry-room','Organize bleach and additives',28),
('laundry-room','Store cleaning cloths',29),
('laundry-room','Label storage containers',30),
('laundry-room','Clean ventilation',31),
('laundry-room','Organize seasonal laundry items',32),
('laundry-room','Store extra detergent supplies',33),
('laundry-room','Wipe washing machine exterior',34),
('laundry-room','Clean dryer exterior',35),
('laundry-room','Organize spray bottles',36),
('laundry-room','Store iron and ironing board',37),
('laundry-room','Check hoses for leaks',38),
('laundry-room','Organize laundry basket storage',39),
-- living-room-common-areas
('living-room-common-areas','Declutter coffee table',0),
('living-room-common-areas','Organize remote controls & chargers',1),
('living-room-common-areas','Vacuum furniture & cushions',2),
('living-room-common-areas','Straighten pillows & throws',3),
('living-room-common-areas','Dust shelves & decor',4),
('living-room-common-areas','Organize media console',5),
('living-room-common-areas','Clean TV screen',6),
('living-room-common-areas','Organize entertainment center',7),
('living-room-common-areas','Arrange books on shelves',8),
('living-room-common-areas','Fold and store throw blankets',9),
('living-room-common-areas','Organize gaming equipment',10),
('living-room-common-areas','Clean under couch cushions',11),
('living-room-common-areas','Dust light fixtures',12),
('living-room-common-areas','Organize magazines and newspapers',13),
('living-room-common-areas','Clean window blinds',14),
('living-room-common-areas','Arrange decorative items',15),
('living-room-common-areas','Organize board games',16),
('living-room-common-areas','Clean fireplace area',17),
('living-room-common-areas','Vacuum area rugs',18),
('living-room-common-areas','Organize storage baskets',19),
('living-room-common-areas','Dust picture frames',20),
('living-room-common-areas','Clean mirrors',21),
('living-room-common-areas','Organize side table drawers',22),
('living-room-common-areas','Wipe down furniture surfaces',23),
('living-room-common-areas','Organize DVD or Blu-ray collection',24),
('living-room-common-areas','Clean baseboards',25),
('living-room-common-areas','Arrange plants and water them',26),
('living-room-common-areas','Organize charging station',27),
('living-room-common-areas','Clean ceiling fan',28),
('living-room-common-areas','Organize toy storage',29),
('living-room-common-areas','Dust window sills',30),
('living-room-common-areas','Clean light switches',31),
('living-room-common-areas','Organize cords behind TV',32),
('living-room-common-areas','Vacuum behind furniture',33),
('living-room-common-areas','Clean air vents',34),
('living-room-common-areas','Organize photo albums',35),
('living-room-common-areas','Clean ottoman or poufs',36),
('living-room-common-areas','Organize craft supplies',37),
('living-room-common-areas','Dust artwork',38),
('living-room-common-areas','Clean door handles',39),
-- entryway-mudroom
('entryway-mudroom','Organize shoe storage',0),
('entryway-mudroom','Hang coats & bags properly',1),
('entryway-mudroom','Declutter key/mail area',2),
('entryway-mudroom','Wipe down benches & surfaces',3),
('entryway-mudroom','Sweep & mop floor',4),
('entryway-mudroom','Shake out rugs & mats',5),
('entryway-mudroom','Clean entry door inside and out',6),
('entryway-mudroom','Organize umbrella stand',7),
('entryway-mudroom','Wipe mirrors',8),
('entryway-mudroom','Organize hall closet',9),
('entryway-mudroom','Clean baseboards',10),
('entryway-mudroom','Organize seasonal items',11),
('entryway-mudroom','Clean coat hooks',12),
('entryway-mudroom','Wipe light fixtures',13),
('entryway-mudroom','Organize dog leashes and supplies',14),
('entryway-mudroom','Clean doormat thoroughly',15),
('entryway-mudroom','Organize storage bench contents',16),
('entryway-mudroom','Wipe door handles',17),
('entryway-mudroom','Organize scarves and gloves',18),
('entryway-mudroom','Clean console table',19),
('entryway-mudroom','Organize pet supplies',20),
('entryway-mudroom','Dust decorative items',21),
('entryway-mudroom','Organize backpack storage',22),
('entryway-mudroom','Clean light switch',23),
('entryway-mudroom','Organize sports equipment',24),
('entryway-mudroom','Wipe window by door',25),
('entryway-mudroom','Organize reusable shopping bags',26),
('entryway-mudroom','Clean shoe rack',27),
('entryway-mudroom','Organize seasonal decorations',28),
('entryway-mudroom','Vacuum corners and edges',29),
('entryway-mudroom','Organize hat and glove storage',30),
('entryway-mudroom','Clean sidelights or windows',31),
('entryway-mudroom','Organize mail sorting area',32),
('entryway-mudroom','Wipe walls for scuffs',33),
('entryway-mudroom','Organize bike storage',34),
('entryway-mudroom','Clean coat closet floor',35),
('entryway-mudroom','Organize winter boots',36),
('entryway-mudroom','Dust picture frames',37),
('entryway-mudroom','Clean doorbell',38),
('entryway-mudroom','Organize daily essentials basket',39),
-- home-office-desk
('home-office-desk','Declutter desk surface',0),
('home-office-desk','Organize desk drawers',1),
('home-office-desk','Sort papers & file documents',2),
('home-office-desk','Organize cords & cables',3),
('home-office-desk','Dust computer & keyboard',4),
('home-office-desk','Refill office supplies',5),
('home-office-desk','Shred old documents',6),
('home-office-desk','Clean computer monitor',7),
('home-office-desk','Organize pens and pencils',8),
('home-office-desk','Sort through sticky notes',9),
('home-office-desk','Organize filing cabinet',10),
('home-office-desk','Clean desk lamp',11),
('home-office-desk','Arrange bookshelf',12),
('home-office-desk','Organize charging cables',13),
('home-office-desk','Clean office chair',14),
('home-office-desk','Organize printer supplies',15),
('home-office-desk','Sort through mail',16),
('home-office-desk','Organize reference materials',17),
('home-office-desk','Clean keyboard and mouse',18),
('home-office-desk','Wipe down desk surface',19),
('home-office-desk','Organize notebooks',20),
('home-office-desk','Sort through business cards',21),
('home-office-desk','Organize wall calendar',22),
('home-office-desk','Clean windows',23),
('home-office-desk','Vacuum floor',24),
('home-office-desk','Organize magazine holders',25),
('home-office-desk','Clean wastebasket',26),
('home-office-desk','Organize desk organizers',27),
('home-office-desk','Sort through receipts',28),
('home-office-desk','Organize storage boxes',29),
('home-office-desk','Clean baseboards',30),
('home-office-desk','Wipe light switch',31),
('home-office-desk','Organize laptop accessories',32),
('home-office-desk','Clean phone and headset',33),
('home-office-desk','Sort through old invoices',34),
('home-office-desk','Organize stamps and mailers',35),
('home-office-desk','Clean air vent',36),
('home-office-desk','Dust shelves',37),
('home-office-desk','Organize paper clips and binders',38),
('home-office-desk','Clean door and frame',39),
-- storage-areas
('storage-areas','Label all boxes & bins',0),
('storage-areas','Group items by category',1),
('storage-areas','Donate unused items',2),
('storage-areas','Create inventory list',3),
('storage-areas','Vacuum & dust shelves',4),
('storage-areas','Stack boxes efficiently',5),
('storage-areas','Organize holiday decorations',6),
('storage-areas','Sort through old electronics',7),
('storage-areas','Organize tools and hardware',8),
('storage-areas','Clean storage room floor',9),
('storage-areas','Organize seasonal clothing',10),
('storage-areas','Sort through old toys',11),
('storage-areas','Organize camping gear',12),
('storage-areas','Stack bins by season',13),
('storage-areas','Organize craft supplies',14),
('storage-areas','Sort through old photos',15),
('storage-areas','Organize sports equipment',16),
('storage-areas','Clean shelving units',17),
('storage-areas','Organize suitcases and luggage',18),
('storage-areas','Sort through old books',19),
('storage-areas','Organize pet supplies',20),
('storage-areas','Clean light fixtures',21),
('storage-areas','Organize baby items',22),
('storage-areas','Sort through old linens',23),
('storage-areas','Organize wrapping paper and gift bags',24),
('storage-areas','Check for water damage',25),
('storage-areas','Organize paint and supplies',26),
('storage-areas','Sort through old documents',27),
('storage-areas','Organize furniture covers',28),
('storage-areas','Clean cobwebs',29),
('storage-areas','Organize bins by color or type',30),
('storage-areas','Sort through memorabilia',31),
('storage-areas','Organize yard sale items',32),
('storage-areas','Check smoke detector',33),
('storage-areas','Organize extension cords',34),
('storage-areas','Sort through old clothes',35),
('storage-areas','Organize car supplies',36),
('storage-areas','Clean walls and ceiling',37),
('storage-areas','Organize emergency supplies',38),
('storage-areas','Sort through old school materials',39),
-- garage
('garage','Sweep floor',0),
('garage','Organize tools on pegboard',1),
('garage','Group seasonal items together',2),
('garage','Donate or sell unused items',3),
('garage','Clean out car clutter',4),
('garage','Organize sports equipment',5),
('garage','Check for expired items',6),
('garage','Organize workbench',7),
('garage','Sort through hardware and nails',8),
('garage','Clean windows',9),
('garage','Organize garden tools',10),
('garage','Sort through paint cans',11),
('garage','Organize automotive supplies',12),
('garage','Clean garage door',13),
('garage','Organize camping gear',14),
('garage','Sort through old boxes',15),
('garage','Organize lawn care equipment',16),
('garage','Clean shelving units',17),
('garage','Organize bike storage',18),
('garage','Sort through extension cords',19),
('garage','Organize holiday decorations',20),
('garage','Clean light fixtures',21),
('garage','Organize power tools',22),
('garage','Sort through old appliances',23),
('garage','Organize recycling bins',24),
('garage','Clean cobwebs',25),
('garage','Organize winter supplies',26),
('garage','Sort through lumber scraps',27),
('garage','Organize storage bins',28),
('garage','Clean walls',29),
('garage','Organize fishing gear',30),
('garage','Sort through old electronics',31),
('garage','Organize outdoor furniture',32),
('garage','Clean air compressor',33),
('garage','Organize coolers and thermoses',34),
('garage','Sort through scrap metal',35),
('garage','Organize pest control supplies',36),
('garage','Clean ceiling',37),
('garage','Organize safety equipment',38),
('garage','Sort through car maintenance items',39),
-- under-bed-hidden-storage
('under-bed-hidden-storage','Pull out & vacuum under bed',0),
('under-bed-hidden-storage','Use storage bins with labels',1),
('under-bed-hidden-storage','Store only seasonal items',2),
('under-bed-hidden-storage','Avoid food or moisture-sensitive items',3),
('under-bed-hidden-storage','Rotate items seasonally',4),
('under-bed-hidden-storage','Organize winter clothing storage',5),
('under-bed-hidden-storage','Sort through old photos',6),
('under-bed-hidden-storage','Organize gift wrap supplies',7),
('under-bed-hidden-storage','Store off-season shoes',8),
('under-bed-hidden-storage','Organize holiday decorations',9),
('under-bed-hidden-storage','Sort through old blankets',10),
('under-bed-hidden-storage','Organize craft supplies',11),
('under-bed-hidden-storage','Store extra linens',12),
('under-bed-hidden-storage','Organize luggage',13),
('under-bed-hidden-storage','Sort through memorabilia',14),
('under-bed-hidden-storage','Organize board games',15),
('under-bed-hidden-storage','Store baby clothes',16),
('under-bed-hidden-storage','Organize seasonal pillows',17),
('under-bed-hidden-storage','Sort through old toys',18),
('under-bed-hidden-storage','Organize wrapping paper',19),
('under-bed-hidden-storage','Store camping gear',20),
('under-bed-hidden-storage','Organize beach towels',21),
('under-bed-hidden-storage','Sort through old documents',22),
('under-bed-hidden-storage','Organize spare blankets',23),
('under-bed-hidden-storage','Store winter accessories',24),
('under-bed-hidden-storage','Organize craft fabrics',25),
('under-bed-hidden-storage','Sort through old magazines',26),
('under-bed-hidden-storage','Organize costume storage',27),
('under-bed-hidden-storage','Store sports equipment',28),
('under-bed-hidden-storage','Organize extra pillows',29),
('under-bed-hidden-storage','Sort through photo albums',30),
('under-bed-hidden-storage','Organize seasonal throw pillows',31),
('under-bed-hidden-storage','Store pet supplies',32),
('under-bed-hidden-storage','Organize yoga mats',33),
('under-bed-hidden-storage','Sort through old electronics',34),
('under-bed-hidden-storage','Organize gift bags',35),
('under-bed-hidden-storage','Store picnic supplies',36),
('under-bed-hidden-storage','Organize sewing supplies',37),
('under-bed-hidden-storage','Sort through old books',38),
('under-bed-hidden-storage','Check for dust buildup',39),
-- digital-home-organization
('digital-home-organization','Clean email inbox',0),
('digital-home-organization','Organize phone photos',1),
('digital-home-organization','Delete unused apps',2),
('digital-home-organization','Back up important files',3),
('digital-home-organization','Organize cloud storage',4),
('digital-home-organization','Unsubscribe from spam emails',5),
('digital-home-organization','Update passwords & security',6),
('digital-home-organization','Organize computer desktop',7),
('digital-home-organization','Sort through downloads folder',8),
('digital-home-organization','Organize bookmarks',9),
('digital-home-organization','Delete duplicate photos',10),
('digital-home-organization','Organize music library',11),
('digital-home-organization','Clean up contacts list',12),
('digital-home-organization','Organize digital receipts',13),
('digital-home-organization','Sort through social media friends',14),
('digital-home-organization','Organize video library',15),
('digital-home-organization','Delete old text messages',16),
('digital-home-organization','Organize notes app',17),
('digital-home-organization','Clean up calendar events',18),
('digital-home-organization','Organize streaming watchlist',19),
('digital-home-organization','Sort through saved articles',20),
('digital-home-organization','Organize digital documents',21),
('digital-home-organization','Delete old voicemails',22),
('digital-home-organization','Organize email folders',23),
('digital-home-organization','Clean up browser history',24),
('digital-home-organization','Organize password manager',25),
('digital-home-organization','Sort through screenshots',26),
('digital-home-organization','Organize digital subscriptions',27),
('digital-home-organization','Delete old emails',28),
('digital-home-organization','Organize podcast library',29),
('digital-home-organization','Clean up desktop shortcuts',30),
('digital-home-organization','Organize digital photos by year',31),
('digital-home-organization','Sort through cloud backups',32),
('digital-home-organization','Organize work files',33),
('digital-home-organization','Delete unused browser extensions',34),
('digital-home-organization','Organize digital recipes',35),
('digital-home-organization','Sort through digital journals',36),
('digital-home-organization','Organize online shopping accounts',37),
('digital-home-organization','Clean up social media posts',38),
('digital-home-organization','Organize digital bills',39),
-- decluttering-donation-prep
('decluttering-donation-prep','Gather items to donate',0),
('decluttering-donation-prep','Sort by donation center requirements',1),
('decluttering-donation-prep','Box & label donation items',2),
('decluttering-donation-prep','Schedule pickup or drop-off',3),
('decluttering-donation-prep','Take photos for tax deduction',4),
('decluttering-donation-prep','Shred personal documents',5),
('decluttering-donation-prep','Sort clothes by condition',6),
('decluttering-donation-prep','Organize items for yard sale',7),
('decluttering-donation-prep','Set aside items to sell online',8),
('decluttering-donation-prep','Sort through old books',9),
('decluttering-donation-prep','Organize toys for donation',10),
('decluttering-donation-prep','Sort through kitchen items',11),
('decluttering-donation-prep','Organize electronics for recycling',12),
('decluttering-donation-prep','Sort through old linens',13),
('decluttering-donation-prep','Organize shoes for donation',14),
('decluttering-donation-prep','Sort through old decorations',15),
('decluttering-donation-prep','Organize bags and purses',16),
('decluttering-donation-prep','Sort through old furniture',17),
('decluttering-donation-prep','Organize sports equipment',18),
('decluttering-donation-prep','Sort through old DVDs and CDs',19),
('decluttering-donation-prep','Organize craft supplies',20),
('decluttering-donation-prep','Sort through old magazines',21),
('decluttering-donation-prep','Organize baby items',22),
('decluttering-donation-prep','Sort through holiday decorations',23),
('decluttering-donation-prep','Organize office supplies',24),
('decluttering-donation-prep','Sort through old photos',25),
('decluttering-donation-prep','Organize tools and hardware',26),
('decluttering-donation-prep','Sort through old cosmetics',27),
('decluttering-donation-prep','Organize cleaning supplies',28),
('decluttering-donation-prep','Sort through old appliances',29),
('decluttering-donation-prep','Organize garden supplies',30),
('decluttering-donation-prep','Sort through old paint cans',31),
('decluttering-donation-prep','Organize camping gear',32),
('decluttering-donation-prep','Sort through old towels',33),
('decluttering-donation-prep','Organize pet supplies',34),
('decluttering-donation-prep','Sort through old accessories',35),
('decluttering-donation-prep','Organize luggage and travel items',36),
('decluttering-donation-prep','Sort through old artwork',37),
('decluttering-donation-prep','Organize musical instruments',38),
('decluttering-donation-prep','Create donation receipt list',39),
-- moving-reset-checklist
('moving-reset-checklist','Deep clean before moving',0),
('moving-reset-checklist','Label all boxes by room',1),
('moving-reset-checklist','Pack essentials box separately',2),
('moving-reset-checklist','Update address & utilities',3),
('moving-reset-checklist','Donate items before packing',4),
('moving-reset-checklist','Take photos of furniture setup',5),
('moving-reset-checklist','Clean new place before unpacking',6),
('moving-reset-checklist','Transfer internet and cable',7),
('moving-reset-checklist','Update mailing address',8),
('moving-reset-checklist','Cancel or transfer subscriptions',9),
('moving-reset-checklist','Pack kitchen first',10),
('moving-reset-checklist','Organize moving truck schedule',11),
('moving-reset-checklist','Sort through and pack closets',12),
('moving-reset-checklist','Pack bathroom essentials last',13),
('moving-reset-checklist','Organize packing materials',14),
('moving-reset-checklist','Take meter readings',15),
('moving-reset-checklist','Clean refrigerator and freezer',16),
('moving-reset-checklist','Organize pet moving arrangements',17),
('moving-reset-checklist','Pack valuables separately',18),
('moving-reset-checklist','Confirm moving company details',19),
('moving-reset-checklist','Prepare children for move',20),
('moving-reset-checklist','Organize parking for moving truck',21),
('moving-reset-checklist','Pack bedrooms by priority',22),
('moving-reset-checklist','Organize change of address cards',23),
('moving-reset-checklist','Clean out storage areas',24),
('moving-reset-checklist','Transfer medical records',25),
('moving-reset-checklist','Pack garage and basement',26),
('moving-reset-checklist','Organize utility turn-off schedule',27),
('moving-reset-checklist','Pack important documents box',28),
('moving-reset-checklist','Clean all appliances',29),
('moving-reset-checklist','Organize keys and remotes',30),
('moving-reset-checklist','Take final meter photos',31),
('moving-reset-checklist','Organize insurance updates',32),
('moving-reset-checklist','Pack decorations carefully',33),
('moving-reset-checklist','Clean windows and blinds',34),
('moving-reset-checklist','Organize first night box',35),
('moving-reset-checklist','Transfer school records',36),
('moving-reset-checklist','Clean out attic',37),
('moving-reset-checklist','Organize final walkthrough',38),
('moving-reset-checklist','Return borrowed items',39);

-- ────────────────────────────────────────────────────────────────────────────
-- 5. Add unique constraint to organization_tasks for idempotent seeding
-- ────────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'organization_tasks_user_section_title_key'
  ) THEN
    ALTER TABLE organization_tasks
      ADD CONSTRAINT organization_tasks_user_section_title_key
      UNIQUE (user_id, section, title);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────────────────
-- 6. Seed function
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION seed_home_org_for_user(p_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_cat  RECORD;
  v_item RECORD;
BEGIN
  FOR v_cat IN
    SELECT c.id, c.icon_name, c.color_tag
    FROM curated_home_org_categories c
    ORDER BY c.sort_order
  LOOP
    FOR v_item IN
      SELECT i.title
      FROM curated_home_org_items i
      WHERE i.category_id = v_cat.id
      ORDER BY i.order_index
    LOOP
      INSERT INTO organization_tasks (user_id, icon, title, section, sub_tasks, completed, color_tag)
      VALUES (
        p_user_id,
        v_cat.icon_name,
        v_item.title,
        v_cat.id,
        '[]'::jsonb,
        false,
        v_cat.color_tag
      )
      ON CONFLICT (user_id, section, title) DO NOTHING;
    END LOOP;
  END LOOP;
END;
$$;

-- ────────────────────────────────────────────────────────────────────────────
-- 7. Backfill all existing users
-- ────────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  v_user RECORD;
BEGIN
  FOR v_user IN SELECT id FROM auth.users
  LOOP
    PERFORM seed_home_org_for_user(v_user.id);
  END LOOP;
END $$;
